sonar.organization=a-ryan-kr
sonar.projectKey=a-ryan-kr
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/database/**,**/kubernetes/**,**/terraform/**,**/*.test.js,**/*.test.tsx,**/*.spec.js,**/*.spec.tsx,**/__tests__/**,**/backend/tests/**
